config/routes.rb
SimpleAuth::Application.routes.draw do
  

  #get "edit/update"
  resources :lists, only: [:index, :create, :update, :destroy]
  resources :invitations, only: [:index, :destroy]
  resources :offers, only: [:index, :destroy]
  resources :updates, only: [:index, :destroy]
  resources :site_of_publics, only: [:index, :destroy]
  resources :app_of_publics, only: [:index, :destroy]
  resources :notices, only: [:index, :destroy]
  resources :edits, only: [:edit]
  resources :partner_apps, only: [:create]
  resources :partner_sites, only: [:create]
  resources :listables, only: [:index]
  resources :partner_apps, only: [:index]
  resources :partner_sites, only: [:index]

  namespace :session do
    get "landing"
    get "signin"
    get "signup"
    get "update"
    get "passup"
    get "preset"
    post "authorize"
    post "amend"
    post "add"
    post "alter"
    get "abandon"
    post "ask"
    post "abolish"
    get "about"
    get "download"
    post "mail"
  end

  get "/auth/:provider/callback", :to => "session#create"
  get "/auth/failure", :to => "session#failure"

  get "/mobiles/list/:list_id", :to => "mobiles#list"
  namespace :mobiles do
    get "landing" 
    post "login"
    get "logout"
    get "lists"
  end
  
  namespace :apis do
    get "app_publics/:partner_app_id", :to =>"api#app_publics"
    get "site_publics/:partner_site_id", :to =>"api#site_publics"
    post "invite/:public_id", :to =>"api#invite"
    post "offer/:public_id", :to =>"api#offer"
    post "update/:public_id", :to =>"api#update"
    get "lists/:listable_id" , :to =>"api#lists"
    get "list/:list_id", :to =>"api#list"
    get "publics/:public_id/list/:list_id", :to =>"api#publics_list"
    get "publics/:public_id", :to =>"api#publics"
    get "publics_lists/:public_id/", :to =>"api#publics_lists"
    get "authorize", :to=>"api#authorize"
    get "adieu", :to=>"api#adieu"
  end
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
  root "session#landing"
end

app/controllers/session_controller.rb
require 'csv'
class SessionController < ApplicationController

  skip_before_action :require_login, only: [:landing, :signin, :signup,\
   :authorize, :preset, :ask, :abandon, :add, :about, :create, :destroy, :failure]
  include SessionHelper 

  def download
    list = List.where(:name => params['name'], :public_id => session[:user_id]).first
    rows = JSON.parse(list.values).collect{|x| [ list.name, x['item'], "#{x['rating']}" ]}
    rows.unshift %w[list item rating] 
    rows = rows.collect{|row| row.to_csv}.join 
    response.headers['Content-Disposition'] = "attachment; filename=\"#{list.name}.csv\""
    render  :text => rows, :content_type =>  Mime::CSV, :staus => :ok
  end

  def mail
    list = List.where(:name => params['list'], :public_id => session[:user_id]).first
    mail = Mail.new
    message = params['body'] + "\n\n" + format_list(list)
    mail.to params['mail_to']
    mail.from session[:user_email] 
    mail.subject params['subject']
    mail.text_part do
        body message
    end
    mail.deliver
    render :json => 'true' 
  end

  def landing
    extend Rails.application.routes.url_helpers
  end

  def create
    auth_hash = request.env['omniauth.auth']
    render :json => auth_hash
  end
  
  def destroy
    session[:user_id] = nil
    render :text => "You've logged out"
  end
  
  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end

  def about
  end

  def signin
  end

  def signup
    @values = {}
    render :signup
  end

  def update
    account = stormpath_get_account
    @values = {
      'email' => account.email,
      'href' => account.href,
      'first' => account.given_name,
      'last' => account.surname,
      'zip' => '',
      'year' => '',
      'gender' => ''
      }
    render :update
  end

  def passup

  end

  def preset
  end

  def amend
    amended = stormpath_update_account params
    if amended == true
      flash[:notice] = "Your account has been updated."
      redirect_to root_url
    else
      flash[:alert] = amended
      @values = params
      render :update 
    end
  end

  def alter
    altered = stormpath_change_password params['old'], params['new1']
    if altered == true
      flash[:notice] = "You password has been changed."
      redirect_to  root_url 
    else
      flash[:alert] = altered
      render :passup
    end
  end

  def add
    added = stormpath_create_account params
    if added == true
      flash[:notice] = "Your account confirmation email is on the way."
      redirect_to root_url
    else
      flash[:alert] = added
      @values = params
      render :signup
    end
  end

  def authorize
    authorized = stormpath_authenticate_login params['email'], params['password']
    if authorized == true
      publik = Public.find_or_create_by(stormpath_id: session[:user])
      publik.last_login = Time.now.utc
      session[:user_id] = publik.id
      session[:user_email] = params['email']
      flash.clear
      redirect_to  root_url
    else
      puts authorized.to_s
      flash[:alert] = authorized.to_s
      render :signin
    end
  end

  def abandon
    reset_session
    redirect_to root_url
  end

  def ask
    asked = stormpath_request_password_reset params
    if asked == true
      flash[:notice] = "Your password reset email is on the way."
      redirect_to root_url
    else
      flash[:notice] = asked
      render :preset
    end
  end

  def abolish
    stormpath_delete_account
    Public.find_by_stormpath_id(session[:user]).destroy!
    reset_session
    redirect_to root_url
    flash[:notice] = "Your account has been deleted."
  end
end

app/helpers/session_helper.rb
module SessionHelper

	def stormpath_get_application
		key = Stormpath::ApiKey.new(ENV['spkey1'],ENV['spkey2'])
		client = Stormpath::Client.new({:api_key => key})
		return client.applications.get(ENV['spurl'])
	end

	def stormpath_authenticate_login (name, password)
		begin
			application = stormpath_get_application
			auth_request = Stormpath::Authentication::UsernamePasswordRequest.new name, password
			auth_result = application.authenticate_account auth_request
			account = auth_result.account
			session[:user] = account.username
			return true
		rescue => error
			return error.to_s
		end
	end

	def stormpath_get_account
		application = stormpath_get_application
		user = session[:user]
		found = application.accounts.search('username' => user)
		return found.map{|x| x}.first
	end

	def stormpath_update_account params
		begin
			stormpath_get_account.tap do |s|
			  s.email = params['email'],
			  s.surname = params['last'],
			  s.given_name = params['first'],
			  s.save
			end
			return true
		rescue => error
			return error.to_s
		end
	end
	def stormpath_change_password older, newer
		begin
			authentic = stormpath_authenticate_login session['user'], older
			return authentic if authentic != true
			account = stormpath_get_account	
			account.password = newer
			account.save
			return true
		rescue => error
			return error.to_s
		end
	end

	def stormpath_delete_account
		account = stormpath_get_account	
		account.delete
	end

	def stormpath_create_account params
		application = stormpath_get_application
		begin
			account = application.accounts.create({ 
			  given_name: params['first'],
			  surname: params['last'],
			  email: params['email'],
			  password: params['pass1'],
			  username: params['user']
			})
			#no need for save
			return true
		rescue => error
			return error.to_s
		end
	end

	def stormpath_request_password_reset params
		application = stormpath_get_application
		begin
			application.send_password_reset_email params['email']
			return true
		rescue => error
			return error.to_s
		end
	end

	def stormpath_handle_password_reset token
	end

	def stormpath_handle_new_account_confirm token
	end
	def format_list list
	    rows = JSON.parse(list.values).collect{|x| [ list.name, x['item'], "#{x['rating']}" ]}
	    rows.unshift %w[list item rating] 
	    rows = rows.collect do |row|  
	      row.each do |col|
	        '"' + col.gsub('"','""') + '"'
	      end
	      row * "\t"
	    end
	    rows = rows * "\r\n"
    end 
end

app/views/session/about.html.erb
<div class="container">
    <div class="span12" style='text-align:justify'>
        <h2>It's Your Very Own Smart Internet</h2>
        <p class="MsoBodyText">
            Discloze lets you build your own Smart Internet, this is easily done with life lists that explain who you are, what you like, and how you live. Your life lists let the Smart Internet work harder to help you find things, solve problems, and get things done. The Smart Internet is a wonderful way to find deals and discounts, and it's a great way to get suggestions and special offers. Your Smart Internet sites and apps are always just the ones you need, these can do lots of new things in new ways, and they can easily work together as teams.
        </p>
        <h2>Share Your Life Lists On The Smart Internet</h2>
        <p class="MsoBodyText">
            Discloze 
            provides hundreds of different life list choices, these are rated lists of all the interesting and important things in your life, and they're your unique lists for your unique life. The Smart Internet can use your colors list to suggest great outfits, it can use your authors list to suggest great new reads, and it can use your teams list to feed you the sports scores you've got to know.
        </p>
        <h2>You're Always In Total Control Of Your Life Lists</h2>
        <p class="MsoBodyText">Discloze always gives you complete control of your life lists. You can choose any set of life lists to suit yourself, and you can list anything that needs listing. You alone decide how and when to share your public lists with Smart Internet websites and apps, you can also share your protected lists with Facebook friends, but your private lists are strictly for you. Your Smart Internet sites and apps can help you update your public lists, you can email any list or tweet any list item with the push of a button.</p>
        <h2>Get Smart Personalized Offers and Invites</h2>
        <p class="MsoBodyText">
            Discloze make it easy to manage your Smart Offers and Smart Invitations. Some Smart Internet sites and apps will send you special Smart Offers, these offers are strictly limited by you, they're offers tailored to your life, and many will be exclusively for you. Some 
            Smart Internet sites and apps will send you Smart Invitations, these are personalized signup invitations, and it&#39;s easy to find many more signup choices by browsing the Smart Internet site and app catalogs.
        </p>
        <h2>Get Smarter About Yourself and Others</h2>
        <p class="MsoBodyText">
            Discloze life lists are a great tool for learning about yourself; they're a tool for taking stock of your life, understanding who you are, and where your life is going. The best friendships are based on sharing, that's why life list sharing is a great way to strengthen old friendships and build new ones. Your Facebook friends can learn all about you through your public and protected life lists, and you can choose to make your public life lists visible to everyone on Facebook.
        </p>

    </div>
</div>

app/views/session/landing.html.erb
<div class="container">
	<div class="hero-unit" >
		<h1>Welcome To Discloze</h1>
		<p >Disclose is a demonstration site built with Rails 4, Angular, and Bootstrap JS. It's a second generation social site that lets everyone selectively share life lists with both people and programs.</p>
		<p>Some technical highlights include authentication using the Stormpath authentication service, SendGrid mailing, a token authenticated partner API, hybrid Rails/Javascipt processing of form/list pages, and a <a href='<%= mobiles_landing_url %>'>JQuery UI mobile app</a>. This app is deployed on Heroku from a continuous Codeship build. It's monitored by New Relic plus Googe Analytics, and it's tested with RSpec, Cucumber, Capybara, and Poltergeist.</p>
		<p><a href="/auth/facebook" class="btn btn-primary btn-large">Log In wth Facebook &raquo;</a></p>
	</div>
</div>

app/views/session/passup.html.erb
<div class="well css-form" ng-cloak>
	<form role="form" name='changePasswordForm' method='POST' action='<%= session_alter_url %>'>
		<h1>Change Your Password</h1>
		<div class="form-group">
			<label for="old">Current Password</label>
			<input type="password" class="form-control" name="old" required password id='old'
			ng-minlength='3' ng-maxlength='20'
			placeholder="Current Password" ng-model="old">
			<div class="alert alert-danger" ng-show="changePasswordForm.old.$invalid && changePasswordForm.old.$dirty"
			>Please Enter A Valid Password</div>
		</div>
		<div class="form-group">
			<label for="new1">New Password</label>
			<input type="password" class="form-control" name="new1" required password id='new1'
			ng-minlength='3' ng-maxlength='20'
			placeholder="New Password" ng-model="new1">
		</div>
		<div class="alert alert-danger" ng-show="changePasswordForm.new1.$invalid && changePasswordForm.new1.$dirty"
		>Please Enter A Valid Password</div>
		<div class="form-group">
			<label for="new2">Confirm New Password</label>
			<input type="password" class="form-control" name="new2" required password id='new2'
			ng-minlength='3' ng-maxlength='20'
			placeholder="Confirm New Password" ng-model="new2">
		</div>
		<div class="alert alert-danger" ng-show="changePasswordForm.new2.$invalid && changePasswordForm.new2.$dirty"
		>Please Enter A Valid Password</div>
		<div class="alert alert-danger" ng-show="changePasswordForm.new1.$valid && changePasswordForm.new2.$valid && new1!=new2">Passwords Must Match</div>
		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
		<button type="submit" ng-disabled="changePasswordForm.$pristine || changePasswordForm.$invalid || new1!=new2" class="btn btn-success">Change Password</button>
	</form>
</div>

app/views/session/preset.erb
	<div class="well css-form" ng-cloak>
			<form role="form" name='sendResetForm' method='POST' action='<%= session_ask_url %>'>
				<h1>Request Password Reset</h1>
				<div class="form-group">
					<label for="email">Email address</label>
					<input type="email" class="form-control" name="email" required email
					placeholder="Enter Your Email Address" ng-model='email'>
					<div class="alert alert-danger" ng-show="sendResetForm.email.$invalid && sendResetForm.email.$dirty"
					>Please Enter A Valid Email Address </div>
				</div>
				<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
				<button type="submit" ng-disabled="!sendResetForm.$valid" class="btn btn-success">Request</button>
			</form>
		</div>

app/views/session/signin.html.erb
	<div class="well css-form" ng-cloak>
		<form role="form" name='signInForm' method='POST' action='<%= session_authorize_url %>'>
			<h1>Sign In</h1>
			<div class="form-group">
				<label for="email">Email Address</label>
				<input type="email" class="form-control" name="email" required email id="email"
				placeholder="Enter Email Address" ng-model='email'>
			</div>
			<div class="alert alert-danger" ng-show="signInForm.email.$invalid && signInForm.email.$dirty"
			>Please Enter A Valid Email Address </div>
			<div class="form-group">
				<label for="password">Password</label>
				<input type="password" class="form-control" name="password" required password id="password"
				ng-minlength='3' ng-maxlength='20'
				placeholder="Password" ng-model="password">

			</div>
			<div class="alert alert-danger" ng-show="signInForm.password.$invalid && signInForm.password.$dirty"
			>Please Enter A Valid Password</div>
			<div class="checkbox">
				<label>
					<input name='remember' type="checkbox"> Remember Me
				</label>
			</div>
			<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
			<button type="submit" ng-disabled="!signInForm.$valid" class="btn btn-default">Sign In</button>
			<div>
				<a href="<%= session_preset_url %>"><small>forgot your password?</small></a>
			</div>
		</form>
	</div>

app/views/session/signup.html.erb
<script type="text/javascript">
	var signup_controller = function($scope) {
		$scope.user  = '<%= @values['user'] %>';	
		$scope.email = '<%= @values['email'] %>';
		$scope.pass1  = '<%= @values['pass1'] %>';	
		$scope.pass2 = '<%= @values['pass2'] %>';
		$scope.first  = '<%= @values['first'] %>';
		$scope.last  = '<%= @values['last'] %>';
		$scope.zip = parseInt('<%= @values['zip'] %>');
		$scope.year  = parseInt('<%= @values['year'] %>');
		$scope.gender  = '<%= @values['gender'] %>';
		if ($scope.user != '')
		{
			$('#signUpForm').addClass('ng-dirty');
		}
	}
</script>
<div class="well css-form" ng-controller='signup_controller' ng-cloak >
	<form role="form" name='signUpForm' id='signUpForm' method='POST' 
		action='<%= session_add_url %>'>
		<h1>Tell Us About Yourself</h1>
		<div class="form-group">
			<label for="user">Your User Name</label>
			<input type="text" class="form-control" name="user" required text id="user"
			ng-minlength='3' ng-maxlength='20'
			placeholder="Your User Name" ng-model="user">
		</div>
		<div class="alert alert-danger" ng-show="signUpForm.user.$invalid && signUpForm.user.$dirty"
		>Please Enter A Valid User Name</div>
		<div class="form-group">
			<label for="email">Your Email Address</label>
			<input type="email" class="form-control" name="email" required email id='email'
			placeholder="Your Email" ng-model="email">
		</div>
		<div class="alert alert-danger" ng-show="signUpForm.email.$invalid && signUpForm.email.$dirty"
		>Please Enter A Valid Email Address</div>
		<div class="form-group">
			<label for="pass1">Your Password</label>
			<input type="password" class="form-control" name="pass1" required password id="pass1"
			ng-minlength='3' ng-maxlength='20'
			placeholder="New Password" ng-model="pass1">
		</div>
		<div class="alert alert-danger" ng-show="signUpForm.pass1.$invalid && signUpForm.pass1.$dirty"
		>Please Enter A Valid Password</div>
		<div class="form-group">
			<label for="pass2">Confirm Your Password</label>
			<input type="password" class="form-control" name="pass2" required password id="pass2"
			ng-minlength='3' ng-maxlength='20'
			placeholder="Confirm New Password" ng-model="pass2">
		</div>
		<div class="alert alert-danger" ng-show="signUpForm.pass2.$invalid && signUpForm.pass2.$dirty"
		>Please Enter A Valid Password</div>
		<div class="alert alert-danger" ng-show="signUpForm.pass1.$valid && signUpForm.pass2.$valid && pass1!=pass2">Passwords Must Match</div>
		<div class="form-group">
			<label for="first">Your Fist Name</label>
			<input type="text" class="form-control" name="first" required text id="first"
			ng-minlength='3' ng-maxlength='20'
			placeholder="Your First Name" ng-model="first">
		</div>
		<div class="alert alert-danger" ng-show="signUpForm.first.$invalid && signUpForm.first.$dirty"
		>Please Enter A Valid First Name</div>
		<div class="form-group">
			<label for="last">Your Last Name</label>
			<input type="text" class="form-control" name="last" required text id="last"
			ng-minlength='3' ng-maxlength='20'
			placeholder="Your Last Name" ng-model="last">
		</div>
		<div class="alert alert-danger" ng-show="signUpForm.last.$invalid && signUpForm.last.$dirty"
		>Please Enter A Valid Last Name</div>
		<div class="form-group">
			<label for="zip">Your Zip Code (optional)</label>
			<input type="number" class="form-control" name="zip"  number id="zip"
			ng-minlength='5' ng-maxlength='5'
			placeholder="Your Zip Code" ng-model="zip">
		</div>
		<div class="alert alert-danger" ng-show="signUpForm.zip.$invalid && signUpForm.zip.$dirty"
		>Please Correct Your Zip Code</div>
		<div class="form-group">
			<label for="year">Your Birth Year (optional)</label>
			<input type="number" class="form-control" name="year"  number id="year"
			ng-minlength='4' ng-maxlength='4'
			placeholder="Your Birth Year" ng-model="year">
		</div>
		<div class="alert alert-danger" ng-show="signUpForm.year.$invalid && signUpForm.year.$dirty"
		>Please Correct Your Birth Year</div>
		<div class="form-group">
			<label for="gender">Your Gender (optional)<br/>
			<input type="radio" selected='true' name="gender" ng-model="gender" id='unspecified' value="empty" />not specified&nbsp;
			<input type="radio" name="gender"  ng-model="gender" value="male" id='male' />male&nbsp;
			<input type="radio" name="gender"  ng-model="gender" value="female" id='female' />female</label><br/>
		</div>
		<div class="checkbox">
			<label>
				<input name='remember' type="checkbox" ng-model='agree'> I have read and agree to the terms and conditions of this site.
			</label>
		</div>
		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
		<div class="alert alert-danger" ng-show="signUpForm.$valid && !agree">You must agree to the terms and conditions.</div>
		<button type="submit" ng-disabled="signUpForm.$invalid || signUpForm.$pristine || !agree || pass1!=pass2" class="btn btn-success">Create Your Account</button>
	</form>
</div>

app/views/session/update.html.erb
<script type="text/javascript">
	var update_controller = function($scope) {
		$scope.email = '<%= @values['email'] %>';
		$scope.first  = '<%= @values['first'] %>';
		$scope.last  = '<%= @values['last'] %>';
		$scope.zip = parseInt('<%= @values['zip'] %>');
		$scope.year  = parseInt('<%= @values['year'] %>');
		$scope.gender  = '<%= @values['gender'] %>';
		if ($scope.user != '')
		{
			$('#editUserForm').addClass('ng-dirty');
		}
	}
</script>
<div class="well css-form" ng-controller='update_controller' ng-cloak >
	<form role="form" name='editUserForm' id='editUserForm' method='POST' 
	 action='<%= session_amend_url %>' >
		<h1>Update Your Information</h1>
		<div class="form-group">
			<label for="email">Your Email Address</label>
			<input type="email" class="form-control" name="email" required email 
			placeholder="Your Email" ng-model="email">
			<div class="alert alert-danger" ng-show="editUserForm.email.$invalid && editUserForm.email.$dirty"
			>Please Enter A Valid Email Address</div>
		</div>
		<div class="form-group">
			<label for="first">Your Fist Name</label>
			<input type="text" class="form-control" name="first" required text value='abc'
			ng-minlength='3' ng-maxlength='20'
			placeholder="Your First Name" ng-model="first">
			<div class="alert alert-danger" ng-show="editUserForm.first.$invalid && editUserForm.first.$dirty"
			>Please Enter A Valid First Name</div>
		</div>
		<div class="form-group">
			<label for="last">Your Last Name</label>
			<input type="text" class="form-control" name="last" required text
			ng-minlength='3' ng-maxlength='20'
			placeholder="Your Last Name" ng-model="last">
			<div class="alert alert-danger" ng-show="editUserForm.last.$invalid && editUserForm.last.$dirty"
			>Please Enter A Valid Last Name</div>
		</div>
		<div class="form-group">
			<label for="zip">Your Zip Code (optional)</label>
			<input type="number" class="form-control" name="zip"  number
			ng-minlength='5' ng-maxlength='5'
			placeholder="Your Zip Code" ng-model="zip">
		</div>
		<div class="alert alert-danger" ng-show="editUserForm.zip.$invalid && editUserForm.zip.$dirty"
		>Please Correct Your Zip Code</div>
		<div class="form-group">
			<label for="year">Your Birth Year (optional)</label>
			<input type="number" class="form-control" name="year"  number
			ng-minlength='4' ng-maxlength='4'
			placeholder="Your Birth Year" ng-model="year">
		</div>
		<div class="alert alert-danger" ng-show="editUserForm.year.$invalid && editUserForm.year.$dirty"
		>Please Correct Your Birth Year</div>
		<div class="form-group">
			<label for="gender">Your Gender (optional)<br/>
			<input type="radio" selected='true' name="gender" ng-model="gender" value="empty" />not specified&nbsp;
			<input type="radio" name="gender"  ng-model="gender" value="male" />male&nbsp;
			<input type="radio" name="gender"  ng-model="gender" value="female" />female</label><br/>
		</div>
		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
		<button type="submit" ng-disabled="!editUserForm.$valid" class="btn btn-success">Update Your Information</button>
	</form>
</div>
<div>&nbsp;</div>
<div class="well" >
	<form role="form" name='deleteAccountForm'  method='POST' action='<%= session_abolish_url %>'>
		<h1>Delete Your Account Permanently</h1>
		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
		<button type="submit" class="btn btn-danger btn-default">Delete My Account</button>
	</form>
</div>