config/routes.rb
SimpleAuth::Application.routes.draw do
  

  #get "edit/update"
  resources :lists, only: [:index, :create, :update, :destroy]
  resources :invitations, only: [:index, :destroy]
  resources :offers, only: [:index, :destroy]
  resources :updates, only: [:index, :destroy]
  resources :site_of_publics, only: [:index, :destroy]
  resources :app_of_publics, only: [:index, :destroy]
  resources :notices, only: [:index, :destroy]
  resources :edits, only: [:edit]
  resources :partner_apps, only: [:create]
  resources :partner_sites, only: [:create]
  resources :listables, only: [:index]
  resources :partner_apps, only: [:index]
  resources :partner_sites, only: [:index]

  namespace :session do
    get "landing"
    get "signin"
    get "signup"
    get "update"
    get "passup"
    get "preset"
    post "authorize"
    post "amend"
    post "add"
    post "alter"
    get "abandon"
    post "ask"
    post "abolish"
    get "about"
    get "download"
    post "mail"
  end

  get "/auth/:provider/callback", :to => "session#create"
  get "/auth/failure", :to => "session#failure"

  get "/mobiles/list/:list_id", :to => "mobiles#list"
  namespace :mobiles do
    get "landing" 
    post "login"
    get "logout"
    get "lists"
  end
  
  namespace :apis do
    get "app_publics/:partner_app_id", :to =>"api#app_publics"
    get "site_publics/:partner_site_id", :to =>"api#site_publics"
    post "invite/:public_id", :to =>"api#invite"
    post "offer/:public_id", :to =>"api#offer"
    post "update/:public_id", :to =>"api#update"
    get "lists/:listable_id" , :to =>"api#lists"
    get "list/:list_id", :to =>"api#list"
    get "publics/:public_id/list/:list_id", :to =>"api#publics_list"
    get "publics/:public_id", :to =>"api#publics"
    get "publics_lists/:public_id/", :to =>"api#publics_lists"
    get "authorize", :to=>"api#authorize"
    get "adieu", :to=>"api#adieu"
  end
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
  root "session#landing"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Discloze</title>
  <%= csrf_meta_tags %>
  <link id="page_favicon" href="favicon.ico" rel="icon" type="image/x-icon">

  <link href="https://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://angular-ui.github.com/ng-grid/css/ng-grid.css" />
  <script src="https://code.jquery.com/jquery.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>
  <style type="text/css">
      body {
        padding-top: 50px;
      }
      .css-form input.ng-invalid.ng-dirty {
        background-color: #FA787E;
      }
      .css-form input.ng-valid.ng-dirty {
        background-color: #78FA89;
      }
      .notice {
        color:green;
      }
      .alert {
       color: red;
      }
      [ng\:cloak], [ng-cloak], .ng-cloak {
          display: none !important;
        }
  </style>
</head>
<body ng-app='theModule'>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="/">Discloze</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="active"><a href="/">Home</a></li>
            <% if @user -%>
            <li class="dropdown">
              <a href="/" class="dropdown-toggle" data-toggle="dropdown">Your Services <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<%= lists_url %>">My Lists</a></li>
                <li><a href="<%= invitations_url %>">My Invitations</a></li>
                <li><a href="<%= updates_url %>">My Updates</a></li>
                <li><a href="<%= notices_url %>">My Notices</a></li>
                <li><a href="<%= offers_url %>">My Offers</a></li>
                <li class="divider"></li>
                <li><a href="<%= app_of_publics_url %>">My Apps</a></li>
                <li><a href="<%= site_of_publics_url %>">My Sites</a></li>
                <li class="divider"></li>
                <li><a href="<%= listables_url %>">List Catalog</a></li>
                <li><a href="<%= partner_apps_url %>">App Catalog</a></li>
                <li><a href="<%= partner_sites_url %>">Site Catalog</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Your Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
               <li><a href="<%= session_update_url %>">Update You Account Settings</a></li>
               <li><a href="<%= session_passup_url %>">Change Your Password</a></li>
             </ul>
           </li>
           <% end -%>
           <li><a href="<%= session_about_url %>">About</a></li>
         </ul>
        <form class="navbar-form pull-right">
          <% if @user -%>
          <div class="form-group form-inline">
              <span class='text-success'><%=  @user %></span>&nbsp;
              <%= link_to "Sign Out", session_abandon_url, :class=>"btn btn-success form-control"%>
            </div>
          <% else -%>
          <div class="form-group form-inline">
              <%= link_to "Sign In", session_signin_url ,:class=>"btn btn-success form-control"%>
              <%= link_to "Sign Up", session_signup_url, :class=>"btn btn-success form-control"%>
          </div>
          <% end -%>
        </form>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
  <div class="container starter-tempate">
    <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
    <% end -%>
  </div>
  <div class="container">
    <%= yield %>
  </div>

  <script src="https://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
  <script src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.6.0.js"></script>
  <script type="text/javascript" src="http://angular-ui.github.com/ng-grid/lib/ng-grid.debug.js"></script>
  <%= javascript_include_tag "application"%>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-44826961-1', 'discloze.herokuapp.com');
    ga('send', 'pageview');
  </script>
</body>

</html>